stages:
  - build
  - deploy

build:
  script:
    - echo "Running the build process..."
  when: on_failure
  after_script:
    - curl -X POST -H 'Content-type: application/json' --data '{"text":"Pipeline failed in GitLab! Please check the details."}' $SLACK_WEBHOOK_URL

deploy:
  script:
    - echo "Deploying the application..."
  when: on_failure
  after_script:
    - curl -X POST -H 'Content-type: application/json' --data '{"text":"Pipeline failed in GitLab! Please check the details."}' $SLACK_WEBHOOK_URL
